services:
  app:
    build: .
    container_name: attribution-tracking
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST_URL=${HOST_URL}
      - SECRET_KEY=${SECRET_KEY}
      - MONGODB_URI=mongodb://mongo:27017/AttributionTracking
      - GA4_PROPERTY_ID=${GA4_PROPERTY_ID}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GA4_CREDENTIALS=${GA4_CREDENTIALS}
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    command: npm run start

  mongo:
    image: mongo:6
    container_name: mongo
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
